# Generated by Django 2.2 on 2019-04-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190422_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='asked_by',
        ),
    ]
