# Generated by Django 2.2 on 2019-04-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_question_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Major',
            field=models.CharField(choices=[('Acc', 'Accounting'), ('Anthro', 'Anthropology'), ('Math', 'Applied Mathematics'), ('Art', 'Art'), ('Biochemistry', 'Biochemistry'), ('Biology', 'Biology'), ('Business', 'Business Administration'), ('Computer', 'Computer Science'), ('Criminal Intelligence', 'Criminal Intelligence Analysis')], default='', max_length=2),
        ),
    ]
