# Generated by Django 2.2 on 2019-04-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_question_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered',
        ),
    ]
