# Generated by Django 2.2 on 2019-04-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_question_asked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
