# Generated by Django 2.2 on 2019-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_answer_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
