# Generated by Django 2.2 on 2019-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190425_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
